title: OpenOnDemand (OOD) Tutorial
description: Research Computing OOD documentation
theme: just-the-docs

url: https://fandm-college.github.io
baseurl: ood

# Callout configuration
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red